# Staging Resource Quota
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: staging-quota
  namespace: staging
spec:
  hard:
    requests.cpu: "3"
    requests.memory: "4Gi"
    limits.cpu: "3"
    limits.memory: "8Gi"
