# Grafana Service for Production
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: production
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
