# Grafana Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
          resources:
            requests:
              memory: "32Mi" # Reduced from 64Mi
              cpu: "20m" # Reduced from 100m
            limits:
              memory: "128Mi" # Same as before
              cpu: "50m" # Reduced from 200m
      volumes:
        - name: grafana-storage
          emptyDir: {}
