# PostgreSQL StatefulSet
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: trendline-database
  namespace: development
spec:
  serviceName: trendline-database
  replicas: 1
  selector:
    matchLabels:
      app: trendline-database
  template:
    metadata:
      labels:
        app: trendline-database
    spec:
      containers:
        - name: trendline-database
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: YourStrong!Passw0rd
            - name: POSTGRES_DB
              value: TrendLineDB
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: "128Mi" # Minimum guaranteed memory
              cpu: "100m" # Minimum guaranteed CPU
            limits:
              memory: "256Mi" # Maximum allowed memory
              cpu: "200m" # Maximum allowed CPU
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
