# Backend Deployment for Development
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trendline-backend
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trendline-backend
  template:
    metadata:
      labels:
        app: trendline-backend
    spec:
      containers:
        - name: trendline-backend
          image: trendline-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ConnectionStrings__DefaultConnection
              value: "Host=trendline-database;Port=5432;Database=TrendLineDB;Username=postgres;Password=YourStrong!Passw0rd"
            - name: Solr__Url
              value: "http://trendline-solr:8983/solr/clothing_shop_core"
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "100m"
