# Backend Secret for Development
---
apiVersion: v1
kind: Secret
metadata:
  name: trendline-db-credentials
  namespace: development
type: Opaque
data:
  connection-string: SG9zdD10cmVuZGxpbmUtZGF0YWJhc2U7UG9ydD01NDMyO0RhdGFiYXNlPVRyZW5kTGluZURCO1VzZXJuYW1lPXBvc3RncmVzO1Bhc3N3b3JkPVlvdXJTdHJvbmchUGFzc3cwcmQ=
