# Backend Deployment for Development
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trendline-backend
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trendline-backend
  template:
    metadata:
      labels:
        app: trendline-backend
    spec:
      containers:
        - name: trendline-backend
          image: trendline-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: trendline-backend-config
                  key: ASPNETCORE_ENVIRONMENT
            - name: ConnectionStringsDefaultConnection
              valueFrom:
                secretKeyRef:
                  name: trendline-db-credentials
                  key: connection-string
            - name: SolrUrl
              valueFrom:
                configMapKeyRef:
                  name: trendline-backend-config
                  key: SolrUrl
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "100m"
