# Prometheus Service for Production
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: production
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
