# Prometheus VPA for Production
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: prometheus-vpa
  namespace: production
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: prometheus
  updatePolicy:
    updateMode: "Off" # Recommendation mode only
  resourcePolicy:
    containerPolicies:
      - containerName: "*"
        minAllowed:
          cpu: 50m
          memory: 512Mi
        maxAllowed:
          cpu: 200m
          memory: 4Gi
