# Frontend VPA for Staging
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: frontend-vpa
  namespace: staging
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: trendline-frontend
  updatePolicy:
    updateMode: "Off"
  resourcePolicy:
    containerPolicies:
      - containerName: "*"
        minAllowed:
          cpu: 100m
          memory: 64Mi
        maxAllowed:
          cpu: 500m
          memory: 512Mi
