# Frontend Deployment for Production
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trendline-frontend
  namespace: production
spec:
  replicas: 3 # At least 3 pods for production
  strategy:
    type: RollingUpdate # Zero-downtime deployments
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: trendline-frontend
  template:
    metadata:
      labels:
        app: trendline-frontend
    spec:
      containers:
        - name: trendline-frontend
          image: trendline-frontend:v7 # Using the same version as staging
          imagePullPolicy: IfNotPresent # Always pull in production
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "256Mi" # Increased from staging
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "100m"
