# Backend HPA for Staging
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: staging
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: trendline-backend
  minReplicas: 3 # Maintain minimum 3 pods as required for staging
  maxReplicas: 6 # Allow scaling up to 6 pods based on load
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70 # Scale when average CPU utilization reaches 70%
