# Database Service Alias for Staging
---
apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: production
spec:
  selector:
    app: trendline-database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
