apiVersion: v1
kind: Service
metadata:
  name: trendline-database
  namespace: production # Changed namespace
spec:
  selector:
    app: trendline-database
  ports:
    - protocol: TCP
      port: 5432
