# PostgreSQL StatefulSet for Staging
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: trendline-database
  namespace: staging
spec:
  serviceName: trendline-database
  replicas: 3
  selector:
    matchLabels:
      app: trendline-database
  template:
    metadata:
      labels:
        app: trendline-database
    spec:
      containers:
        - name: trendline-database
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: trendline-db-credentials
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: trendline-db-credentials
                  key: postgres-password
            - name: POSTGRES_DB
              value: TrendLineDB
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: "200Mi"
              cpu: "100m"
            limits:
              memory: "400Mi"
              cpu: "200m"
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 20Gi
