# PostgreSQL Service for Staging
---
apiVersion: v1
kind: Service
metadata:
  name: trendline-database
  namespace: staging
spec:
  selector:
    app: trendline-database
  ports:
    - protocol: TCP
      port: 5432
