# Backend Deployment for Production
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trendline-backend
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: trendline-backend
  template:
    metadata:
      labels:
        app: trendline-backend
    spec:
      containers:
        - name: trendline-backend
          image: vuki123/trendline-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: trendline-backend-config
                  key: ASPNETCORE_ENVIRONMENT
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: trendline-db-credentials
                  key: connection-string
            - name: Solr__Url
              valueFrom:
                configMapKeyRef:
                  name: trendline-backend-config
                  key: Solr__Url
          resources:
            requests:
              memory: "512Mi"
              cpu: "50m"
            limits:
              memory: "1Gi"
              cpu: "100m"
