# Backend Service for Production
---
apiVersion: v1
kind: Service
metadata:
  name: trendline-backend
  namespace: production
spec:
  type: NodePort
  selector:
    app: trendline-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 80
