# Frontend Deployment for Development
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trendline-frontend
  namespace: development
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: trendline-frontend
  template:
    metadata:
      labels:
        app: trendline-frontend
    spec:
      containers:
        - name: trendline-frontend
          image: vuki123/trendline-frontend:v7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/nginx/html/config.js
              subPath: config.js
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
