# Solr Persistent Volume
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: solr-data-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/solr-data
---

